parameters:
    ped_storage.uploader: "ped_storage.%env(STORAGE_ADAPTER)%_media_handler"

ped_storage:
    amazon_s3:
        key:         "%env(STORAGE_AMAZON_S3_KEY)%"
        secret:      "%env(STORAGE_AMAZON_S3_SECRET)%"
        region:      "%env(STORAGE_AMAZON_S3_REGION)%"
        endpoint:    "%env(STORAGE_AMAZON_S3_ENDPOINT)%"
        bucket_name: "%env(STORAGE_AMAZON_S3_BUCKET_NAME)%"
        directory:   "%env(STORAGE_AMAZON_S3_DIRECTORY)%"
        expire_at:   "%env(STORAGE_AMAZON_S3_EXPIRE_AT)%"
        thumbs_prefix: "%env(STORAGE_AMAZON_S3_THUMBS_PREFIX)%"
    local:
        endpoint:      "%env(STORAGE_LOCAL_ENDPOINT)%"
        directory:     "%kernel.root_dir%/../public/%env(STORAGE_LOCAL_DIRECTORY)%"
        thumbs_prefix: "%env(STORAGE_LOCAL_THUMBS_PREFIX)%"